/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.conCustomerInfo;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author buddi
 */
public class CustomerInfo extends javax.swing.JFrame {

    /**
     * Creates new form CustomerInfo
     */
    public CustomerInfo() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.white);
        new conCustomerInfo().setReloadCustomerTable(tbl_ciTalble);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ciTalble = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_ciAdd = new javax.swing.JButton();
        btn_ciEdit = new javax.swing.JButton();
        btn_ciDelete = new javax.swing.JButton();
        txtf_ciRoomID = new javax.swing.JTextField();
        txtf_ciName = new javax.swing.JTextField();
        txtf_ciAddress = new javax.swing.JTextField();
        txtf_ciPhone = new javax.swing.JTextField();
        cmb_ciType = new javax.swing.JComboBox();
        btn_ciClear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cmb_ciGuests = new javax.swing.JComboBox();
        dtc_ciCheckIn = new com.toedter.calendar.JDateChooser();
        dtc_ciCheckOut = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtf_ciNIC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customer Information");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tbl_ciTalble.setGridColor(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(tbl_ciTalble);

        jLabel2.setText("Room No");

        jLabel3.setText("Address");

        jLabel4.setText("Name");

        jLabel5.setText("Phone No");

        jLabel6.setText("Type");

        btn_ciAdd.setText("Add");
        btn_ciAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ciAddActionPerformed(evt);
            }
        });

        btn_ciEdit.setText("Update");
        btn_ciEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ciEditActionPerformed(evt);
            }
        });

        btn_ciDelete.setText("Delete");
        btn_ciDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ciDeleteActionPerformed(evt);
            }
        });

        txtf_ciRoomID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtf_ciRoomIDKeyReleased(evt);
            }
        });

        txtf_ciName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtf_ciNameKeyReleased(evt);
            }
        });

        txtf_ciAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtf_ciAddressKeyReleased(evt);
            }
        });

        txtf_ciPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtf_ciPhoneKeyReleased(evt);
            }
        });

        cmb_ciType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Double", "Deluxe", "Suite" }));

        btn_ciClear.setText("Clear Fields");

        jLabel7.setText("Guests");

        cmb_ciGuests.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "1", "2", "3", "4", "5" }));

        jLabel8.setText("Check In");

        jLabel9.setText("Check Out");

        jLabel10.setText("NIC");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(btn_ciAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_ciEdit)
                                .addGap(18, 18, 18)
                                .addComponent(btn_ciDelete))
                            .addComponent(txtf_ciName)
                            .addComponent(txtf_ciAddress)
                            .addComponent(txtf_ciPhone)
                            .addComponent(cmb_ciType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_ciGuests, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dtc_ciCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtf_ciRoomID)
                            .addComponent(dtc_ciCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtf_ciNIC)))
                    .addComponent(btn_ciClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtf_ciNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtf_ciRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtf_ciName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtf_ciAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtf_ciPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmb_ciType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmb_ciGuests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dtc_ciCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dtc_ciCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ciAdd)
                    .addComponent(btn_ciEdit)
                    .addComponent(btn_ciDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ciClear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resoureces/customerinfo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtf_ciRoomIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_ciRoomIDKeyReleased
        new conCustomerInfo().setPopulateCustomerTable(tbl_ciTalble, "roomNo", txtf_ciRoomID); // TODO add your handling code here:
    }//GEN-LAST:event_txtf_ciRoomIDKeyReleased

    private void txtf_ciNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_ciNameKeyReleased
        new conCustomerInfo().setPopulateCustomerTable(tbl_ciTalble, "name", txtf_ciName);        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_ciNameKeyReleased

    private void txtf_ciAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_ciAddressKeyReleased
        new conCustomerInfo().setPopulateCustomerTable(tbl_ciTalble, "address", txtf_ciAddress);// TODO add your handling code here:
    }//GEN-LAST:event_txtf_ciAddressKeyReleased

    private void txtf_ciPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtf_ciPhoneKeyReleased
        new conCustomerInfo().setPopulateCustomerTable(tbl_ciTalble, "phoneNo", txtf_ciPhone);// TODO add your handling code here:
    }//GEN-LAST:event_txtf_ciPhoneKeyReleased

    private void btn_ciDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ciDeleteActionPerformed
        new conCustomerInfo().setCustomerDELETE(tbl_ciTalble);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ciDeleteActionPerformed

    private void btn_ciAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ciAddActionPerformed
        if (txtf_ciName.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Must have name");
        } else if (txtf_ciPhone.getText().length() < 10) {
            JOptionPane.showMessageDialog(null, "Must atleast 10 characters");
        } else if (txtf_ciAddress.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Must have name");
        } else if (dtc_ciCheckIn.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Must have Check In date");
        } else if (dtc_ciCheckOut.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Must have Check Out date");
        } else if (txtf_ciRoomID.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Must have entered rooms");
        } else {
            new conCustomerInfo().setCustomerIN(txtf_ciNIC, txtf_ciRoomID.getText(), txtf_ciName, txtf_ciAddress.getText(), txtf_ciPhone, cmb_ciType, cmb_ciGuests, dtc_ciCheckIn, dtc_ciCheckOut, tbl_ciTalble);
        }// TODO add your handling code here:
    }//GEN-LAST:event_btn_ciAddActionPerformed

    private void btn_ciEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ciEditActionPerformed
        new conCustomerInfo().setCustomerUPDATE(tbl_ciTalble);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ciEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ciAdd;
    private javax.swing.JButton btn_ciClear;
    private javax.swing.JButton btn_ciDelete;
    private javax.swing.JButton btn_ciEdit;
    private javax.swing.JComboBox cmb_ciGuests;
    private javax.swing.JComboBox cmb_ciType;
    private com.toedter.calendar.JDateChooser dtc_ciCheckIn;
    private com.toedter.calendar.JDateChooser dtc_ciCheckOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_ciTalble;
    private javax.swing.JTextField txtf_ciAddress;
    private javax.swing.JTextField txtf_ciNIC;
    private javax.swing.JTextField txtf_ciName;
    private javax.swing.JTextField txtf_ciPhone;
    private javax.swing.JTextField txtf_ciRoomID;
    // End of variables declaration//GEN-END:variables
}
