/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.JOptionPane;
import model.DBM;
import model.ForgetPass;
import view.Login;

/**
 *
 * @author BILLODI
 */
public class ForgetPassword extends javax.swing.JFrame {
    
    static int pin = 0;

    /**
     * Creates new form forgetpassform
     */
    public ForgetPassword() {
        initComponents();
        
        passwordPane.hide();
        pinPane.hide();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        btn_spin = new javax.swing.JButton();
        pinPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_pin = new javax.swing.JTextField();
        btn_gpin = new javax.swing.JButton();
        passwordPane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_spass = new javax.swing.JButton();
        txp_spass = new javax.swing.JPasswordField();
        txp_cpass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forgot Password");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailPane.setBackground(new java.awt.Color(255, 255, 255));
        emailPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Enter your email corrisponding to your account");
        emailPane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 18));

        txt_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailPane.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 265, -1));

        btn_spin.setText("Send pin");
        btn_spin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_spinActionPerformed(evt);
            }
        });
        emailPane.add(btn_spin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        getContentPane().add(emailPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 181));

        pinPane.setBackground(new java.awt.Color(255, 255, 255));
        pinPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Enter Your pin");
        pinPane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 110, 18));

        txt_pin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pinPane.add(txt_pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 265, -1));

        btn_gpin.setText("Enter pin");
        btn_gpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gpinActionPerformed(evt);
            }
        });
        pinPane.add(btn_gpin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        getContentPane().add(pinPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 181));

        passwordPane.setBackground(new java.awt.Color(255, 255, 255));
        passwordPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Create new password");
        passwordPane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, 130, 20));

        jLabel4.setText("Confirm new password");
        passwordPane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, 140, 20));

        btn_spass.setText("Set Password");
        btn_spass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_spassActionPerformed(evt);
            }
        });
        passwordPane.add(btn_spass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 150, -1));

        txp_spass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordPane.add(txp_spass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 120, -1));

        txp_cpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordPane.add(txp_cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 120, 20));

        getContentPane().add(passwordPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 181));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_spinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_spinActionPerformed
        
        try {
            Random rand = new Random(); //instance of random class
            int upperbound = 9999;
            pin = rand.nextInt(upperbound);
            ResultSet r = DBM.search("SELECT * FROM staffInfo WHERE email='" + txt_email.getText() + "'");
            if (r.next()) {
                ForgetPass.to_mail = txt_email.getText();
                ForgetPass.recov_pin = String.valueOf(pin);
                ForgetPass.fp();
                if (ForgetPass.sent_or_not) {
                    pinPane.show();
                    emailPane.hide();
                    JOptionPane.showMessageDialog(this, "Email sent successfully", "Successful", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Email sent failed", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_spinActionPerformed

    private void btn_spassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_spassActionPerformed
        try {
            if (txp_spass.getText().equals(txp_cpass.getText())) {
                DBM.iud("UPDATE staffInfo SET password = '"+txp_spass.getText()+"' WHERE email = '"+txt_email.getText()+"';");
                JOptionPane.showMessageDialog(this, "Password changed successfully", "Successful", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                new Login().setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_spassActionPerformed

    private void btn_gpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gpinActionPerformed
        
        if (txt_pin.getText().equals(String.valueOf(pin))) {
            passwordPane.show();
            pinPane.hide();
        } else {
            JOptionPane.showMessageDialog(this, "Wrong pin", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_gpinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_gpin;
    private javax.swing.JButton btn_spass;
    private javax.swing.JButton btn_spin;
    private javax.swing.JPanel emailPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel passwordPane;
    private javax.swing.JPanel pinPane;
    private javax.swing.JPasswordField txp_cpass;
    private javax.swing.JPasswordField txp_spass;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_pin;
    // End of variables declaration//GEN-END:variables
}
