/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Buddika Alwis
 */
public class Test1 extends javax.swing.JFrame {

    static boolean b = false;
    static int hi = 0;
    static int wi = 0;

    /**
     * Creates new form test
     */
    public Test1() {
        hi = 200;
        wi = 100;
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
        jLabel1.setLocation(hi,wi);
        jLabel1.requestFocus();
        idle(jLabel1);
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setOpaque(true);
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel1KeyReleased(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 200, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyPressed
        if (String.valueOf(evt.getKeyChar()).equals("h")) {
            b = true;
            
            animation(jLabel1,"Attack",140);
        }
        if (String.valueOf(evt.getKeyChar()).equals("j")) {
            b = true;
            
            animation(jLabel1,"Jump",112);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1KeyPressed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyPressed

    private void jLabel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test1().setVisible(true);

            }
        });
    }

    public static void idle(JLabel j) {

        Thread t = new Thread() {
            public void run() {
                int i = 0;
                try {
                    while (true) {
                        if (b) {
                            
                            break;
                        }
                        j.setLocation(hi, wi);
                        ImageIcon icon = new ImageIcon("src/resources/Idle__00" + String.valueOf(i) + ".png");
                        Image image = icon.getImage();
                        Image newimg = image.getScaledInstance(80, 160, Image.SCALE_SMOOTH);
                        icon = new ImageIcon(newimg);
                        j.setIcon(icon);
                        i = i + 1;
                        if (i > 9) {
                            i = 0;
                        }
                        Thread.sleep(80);
                        
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        };
        t.start();

    }

    public static void animation(JLabel j,String action,int wide) {
        Thread t = new Thread() {
            public void run() {
                
                int i = 0;
                try {
                    while (i < 10) {
                        ImageIcon icon = new ImageIcon("src/resources/"+action+"__00" + String.valueOf(i) + ".png");
                        Image image = icon.getImage();
                        Image newimg = image.getScaledInstance(wide, 160, Image.SCALE_SMOOTH);
                        icon = new ImageIcon(newimg);
                        j.setIcon(icon);
                        i = i + 1;
                            j.setLocation(hi, wi);
                        Thread.sleep(80);

                    }
                    b = false;

                    Test1.idle(j);

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        };
        t.start();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
